# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: spring
services:
  mariadb:
    extends:
      file: ./mariadb.yml
      service: mariadb
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
  redis:
    extends:
      file: ./redis.yml
      service: redis
  consul:
    extends:
      file: ./consul.yml
      service: consul
  consul-config-loader:
    extends:
      file: ./consul.yml
      service: consul-config-loader
